name: Build 7zip DLL

on:
  workflow_call:

jobs:
  build_7zip:
    runs-on: windows-2022

    strategy:
        matrix:
          target: [ Release ]

    env:
      ARTIFACTS_DIR: ${{ github.workspace }}\build\artifacts\7zip
      PROJECT_NAME: 7zip-x64-${{ matrix.target }}

    steps:
    - uses: actions/checkout@v4

    - name: Build 7zip x64
      shell: powershell
      run: |
        cmake -B Build -DCMAKE_BUILD_NUMBER=${{ github.run_number }}
        cmake --build Build --config ${{ matrix.target }}

    - name: Run tests
      shell: powershell
      run: |
        ctest --test-dir Build -C ${{ matrix.target }} -VV

    - name: Zip output folder
      run: |
        7z a -t7z -mx=9 "${{ env.ARTIFACTS_DIR }}\${{ env.PROJECT_NAME }}.7z" "${{ github.workspace }}\Output\x64\${{ matrix.target }}\*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}
        path: ${{ env.ARTIFACTS_DIR }}\${{ env.PROJECT_NAME }}.7z
        retention-days: 7
