name: "Build 7zip DLL"

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build_7zip:
    runs-on: windows-2022

    strategy:
        matrix:
          target: [ Debug, Release ]

    env:
      ARTIFACTS_DIR: ${{ github.workspace }}\build\artifacts\7zip
      PROJECT_NAME: 7zip-x64-${{ matrix.target }}

    steps:
    - uses: actions/checkout@v4

    - uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    - name: Build 7zip x64
      shell: powershell
      run: |
        cmake -B Build -DCMAKE_BUILD_NUMBER=${{ github.run_number }}
        cmake --build Build --config ${{ matrix.target }}

    - name: Run tests
      shell: powershell
      run: |
        ctest --test-dir Build -C ${{ matrix.target }} -VV

    - name: Zip artifacts
      run: |
        rclone copy "${{ github.workspace }}\Output\x64\${{ matrix.target }}\*" "${{ env.ARTIFACTS_DIR }}" --ignore-case
        7z a -t7z -mx=9 "${{ env.ARTIFACTS_DIR }}\${{ env.PROJECT_NAME }}.7z" "${{ env.ARTIFACTS_DIR }}\*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}
        path: ${{ env.ARTIFACTS_ROOT_DIR }}/${{ env.PROJECT_NAME }}.7z
        retention-days: 7
