name: "Publish 7zip DLL"

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    secrets: inherit

  publish:
    runs-on: windows-2022
    needs: [build]
    
    env:
      DOWNLOAD_ARTIFACTS_DIR: ${{ github.workspace }}\build\downloaded-artifacts
      UPLOAD_ARTIFACTS_DIR: ${{ github.workspace }}\build\artifacts\7zip
      ARTIFACTS_NAME: 7zip-x64-Release
      GDRIVE_ARTIFACTS_RELEASES_DIR: packages:/aura-av/dependencies/7z/releases

    steps:
    - uses: actions/checkout@v4

    - uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}

    - name: Download artifacts 7zip-x64-Release
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACTS_NAME }}
        path: ${{ env.DOWNLOAD_ARTIFACTS_DIR }}
      
    - name: Unzip files
      run: |
        7z x "${{ env.DOWNLOAD_ARTIFACTS_DIR }}\${{ env.ARTIFACTS_NAME }}.7z" "-o${{ env.DOWNLOAD_ARTIFACTS_DIR }}" -aoa
       
    - name: Set environment variables
      shell: powershell
      run: |
        $BRANCH = "${{ github.ref_name }}"
        $RELEASE = $BRANCH.StartsWith('rev/')
        echo "RELEASE=$RELEASE" | Out-File -FilePath $env:GITHUB_ENV -Append
        
        $Version = ${{ github.workspace }}\Scripts\getVersion.ps1 ${{ github.workspace }}
        echo "PRODUCT_VERSION=$Version" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Zip output folder
      run: |
        rclone copy "${{ env.DOWNLOAD_ARTIFACTS_DIR }}\Binaries" "${{ env.UPLOAD_ARTIFACTS_DIR }}" --include "*.{exe,dll,pdb}" --ignore-case
        7z a -t7z -mx=9 "${{ env.UPLOAD_ARTIFACTS_DIR }}\${{ env.ARTIFACTS_NAME }}.7z" "${{ env.UPLOAD_ARTIFACTS_DIR }}\*"

    # Upload release artifacts to GDrive
    - name: Upload release artifacts
      run: |
        rclone copy "${{ env.UPLOAD_ARTIFACTS_DIR }}\${{ env.ARTIFACTS_NAME }}.7z" "${{ env.GDRIVE_ARTIFACTS_RELEASES_DIR }}/${{ env.PRODUCT_VERSION }}/RC/${{ github.run_id }}"